# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-03 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailYan',
            fields=[
                ('qq', models.IntegerField(primary_key=True, serialize=False, verbose_name='qq')),
                ('img_code', models.CharField(max_length=12, verbose_name='图片验证码')),
                ('email_code', models.IntegerField(null=True, verbose_name='邮箱验证码')),
                ('email_time', models.DateTimeField(auto_now=True, verbose_name='验证码获取时间')),
                ('login_shu', models.IntegerField(default=1, verbose_name='登陆次数')),
                ('huo_shu', models.IntegerField(default=1, verbose_name='获取次数')),
            ],
            options={
                'verbose_name': '邮箱',
                'verbose_name_plural': '邮箱',
                'db_table': 'email_yan',
            },
        ),
        migrations.CreateModel(
            name='Examine',
            fields=[
                ('qq', models.IntegerField(primary_key=True, serialize=False, verbose_name='qq')),
            ],
            options={
                'verbose_name': '审核',
                'verbose_name_plural': '审核',
                'db_table': 'examine',
            },
        ),
        migrations.CreateModel(
            name='ImgList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('img_list', models.TextField(verbose_name='图片列表')),
            ],
        ),
        migrations.CreateModel(
            name='ImgYan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12, verbose_name='验证码')),
                ('path', models.CharField(max_length=100, verbose_name='图片路径')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('qq', models.IntegerField(primary_key=True, serialize=False, verbose_name='QQ')),
                ('name', models.CharField(max_length=39, verbose_name='用户名')),
                ('age', models.CharField(default='男', max_length=3, verbose_name='性别')),
                ('birth_date', models.DateField(default='2020-1-1', verbose_name='生日')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('portrait', models.ImageField(null=True, upload_to='portrait', verbose_name='头像')),
                ('token', models.CharField(max_length=600, verbose_name='Token')),
                ('my_occ', models.IntegerField(default=0, verbose_name='我的职业')),
                ('my_cour_series', models.IntegerField(default=0, verbose_name='我的系列')),
                ('my_cour', models.IntegerField(default=0, verbose_name='我的课程')),
                ('my_res', models.IntegerField(default=0, verbose_name='我的资源')),
                ('my_not', models.IntegerField(default=0, verbose_name='我的笔记')),
                ('coll_occ', models.IntegerField(default=0, verbose_name='收藏的职业')),
                ('coll_cour_series', models.IntegerField(default=0, verbose_name='收藏的系列')),
                ('coll_cour', models.IntegerField(default=0, verbose_name='收藏的课程')),
                ('coll_res', models.IntegerField(default=0, verbose_name='收藏的资源')),
                ('coll_not', models.IntegerField(default=0, verbose_name='收藏的笔记')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'user',
            },
        ),
    ]
