# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-06-06 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200606_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailyan',
            name='qq',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='qq'),
        ),
        migrations.AlterField(
            model_name='examine',
            name='qq',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='qq'),
        ),
    ]
